# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# lesson1python.py
# Created on: 2019-09-12 15:10:59.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: lesson1python <road_feature> <buffer_dist_for_road> <city_feature> <buffer_dist_for_city> <Clip_feature> <Output_feature> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
road_feature = arcpy.GetParameterAsText(0)

buffer_dist_for_road = arcpy.GetParameterAsText(1)
if buffer_dist_for_road == '#' or not buffer_dist_for_road:
    buffer_dist_for_road = "10 Kilometers" # provide a default value if unspecified

city_feature = arcpy.GetParameterAsText(2)

buffer_dist_for_city = arcpy.GetParameterAsText(3)
if buffer_dist_for_city == '#' or not buffer_dist_for_city:
    buffer_dist_for_city = "20 Kilometers" # provide a default value if unspecified

Clip_feature = arcpy.GetParameterAsText(4)

Output_feature = arcpy.GetParameterAsText(5)

# Local variables:
buffer_cities = ""
buffer_roads = ""
US_buffer_Intersect = "H:\\PythonGIS\\Harrison\\Lesson1\\defaultGDB.gdb\\US_buffer_Intersect"

# Process: Buffer
arcpy.Buffer_analysis(city_feature, buffer_cities, buffer_dist_for_city, "FULL", "ROUND", "ALL", "", "PLANAR")

# Process: Buffer (2)
arcpy.Buffer_analysis(road_feature, buffer_roads, buffer_dist_for_road, "FULL", "ROUND", "ALL", "", "PLANAR")

# Process: Intersect
arcpy.Intersect_analysis("# #;# #", US_buffer_Intersect, "ALL", "", "INPUT")

# Process: Clip
arcpy.Clip_analysis(US_buffer_Intersect, Clip_feature, Output_feature, "")

